# Generated by Django 5.1.4 on 2025-03-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pasword',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='pasword',
            field=models.CharField(max_length=50),
        ),
    ]
